/*
* generated by Xtext
*/
package dk.itu.mddp.eank.survey.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import dk.itu.mddp.eank.survey.services.SurveyGrammarAccess;

public class SurveyParser extends AbstractContentAssistParser {
	
	@Inject
	private SurveyGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected dk.itu.mddp.eank.survey.ui.contentassist.antlr.internal.InternalSurveyParser createParser() {
		dk.itu.mddp.eank.survey.ui.contentassist.antlr.internal.InternalSurveyParser result = new dk.itu.mddp.eank.survey.ui.contentassist.antlr.internal.InternalSurveyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getQuestionAccess().getAlternatives(), "rule__Question__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getSurveyAccess().getGroup_3(), "rule__Survey__Group_3__0");
					put(grammarAccess.getSurveyAccess().getGroup_3_1(), "rule__Survey__Group_3_1__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup(), "rule__MultipleChoice__Group__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_4(), "rule__MultipleChoice__Group_4__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_5(), "rule__MultipleChoice__Group_5__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_5_6(), "rule__MultipleChoice__Group_5_6__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_6(), "rule__MultipleChoice__Group_6__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_7(), "rule__MultipleChoice__Group_7__0");
					put(grammarAccess.getMultipleChoiceAccess().getGroup_7_3(), "rule__MultipleChoice__Group_7_3__0");
					put(grammarAccess.getOpenAccess().getGroup(), "rule__Open__Group__0");
					put(grammarAccess.getOpenAccess().getGroup_5(), "rule__Open__Group_5__0");
					put(grammarAccess.getRating_ImplAccess().getGroup(), "rule__Rating_Impl__Group__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_4(), "rule__Rating_Impl__Group_4__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_5(), "rule__Rating_Impl__Group_5__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_6(), "rule__Rating_Impl__Group_6__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_7(), "rule__Rating_Impl__Group_7__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_8(), "rule__Rating_Impl__Group_8__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_9(), "rule__Rating_Impl__Group_9__0");
					put(grammarAccess.getRating_ImplAccess().getGroup_9_3(), "rule__Rating_Impl__Group_9_3__0");
					put(grammarAccess.getRankingAccess().getGroup(), "rule__Ranking__Group__0");
					put(grammarAccess.getRankingAccess().getGroup_3(), "rule__Ranking__Group_3__0");
					put(grammarAccess.getRankingAccess().getGroup_4(), "rule__Ranking__Group_4__0");
					put(grammarAccess.getRankingAccess().getGroup_4_3(), "rule__Ranking__Group_4_3__0");
					put(grammarAccess.getRankingAccess().getGroup_8(), "rule__Ranking__Group_8__0");
					put(grammarAccess.getDichotomousAccess().getGroup(), "rule__Dichotomous__Group__0");
					put(grammarAccess.getDichotomousAccess().getGroup_4(), "rule__Dichotomous__Group_4__0");
					put(grammarAccess.getDichotomousAccess().getGroup_5(), "rule__Dichotomous__Group_5__0");
					put(grammarAccess.getDichotomousAccess().getGroup_5_3(), "rule__Dichotomous__Group_5_3__0");
					put(grammarAccess.getDichotomousAccess().getGroup_6(), "rule__Dichotomous__Group_6__0");
					put(grammarAccess.getDichotomousAccess().getGroup_6_3(), "rule__Dichotomous__Group_6_3__0");
					put(grammarAccess.getSumConstantAccess().getGroup(), "rule__SumConstant__Group__0");
					put(grammarAccess.getSumConstantAccess().getGroup_4(), "rule__SumConstant__Group_4__0");
					put(grammarAccess.getStapleAccess().getGroup(), "rule__Staple__Group__0");
					put(grammarAccess.getStapleAccess().getGroup_4(), "rule__Staple__Group_4__0");
					put(grammarAccess.getStapleAccess().getGroup_5(), "rule__Staple__Group_5__0");
					put(grammarAccess.getStapleAccess().getGroup_6(), "rule__Staple__Group_6__0");
					put(grammarAccess.getStapleAccess().getGroup_7(), "rule__Staple__Group_7__0");
					put(grammarAccess.getStapleAccess().getGroup_8(), "rule__Staple__Group_8__0");
					put(grammarAccess.getStapleAccess().getGroup_9(), "rule__Staple__Group_9__0");
					put(grammarAccess.getStapleAccess().getGroup_10(), "rule__Staple__Group_10__0");
					put(grammarAccess.getStapleAccess().getGroup_10_3(), "rule__Staple__Group_10_3__0");
					put(grammarAccess.getMultipleChoiceForkAccess().getGroup(), "rule__MultipleChoiceFork__Group__0");
					put(grammarAccess.getMultipleChoiceForkAccess().getGroup_3(), "rule__MultipleChoiceFork__Group_3__0");
					put(grammarAccess.getMultipleChoiceForkAccess().getGroup_3_3(), "rule__MultipleChoiceFork__Group_3_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getRatingForkAccess().getGroup(), "rule__RatingFork__Group__0");
					put(grammarAccess.getRatingForkAccess().getGroup_3(), "rule__RatingFork__Group_3__0");
					put(grammarAccess.getRatingForkAccess().getGroup_4(), "rule__RatingFork__Group_4__0");
					put(grammarAccess.getRatingForkAccess().getGroup_5(), "rule__RatingFork__Group_5__0");
					put(grammarAccess.getRatingForkAccess().getGroup_5_3(), "rule__RatingFork__Group_5_3__0");
					put(grammarAccess.getRankingForkAccess().getGroup(), "rule__RankingFork__Group__0");
					put(grammarAccess.getRankingForkAccess().getGroup_2(), "rule__RankingFork__Group_2__0");
					put(grammarAccess.getRankingForkAccess().getGroup_3(), "rule__RankingFork__Group_3__0");
					put(grammarAccess.getRankingForkAccess().getGroup_6(), "rule__RankingFork__Group_6__0");
					put(grammarAccess.getRankingForkAccess().getGroup_6_3(), "rule__RankingFork__Group_6_3__0");
					put(grammarAccess.getModelAccess().getSurveysAssignment_1(), "rule__Model__SurveysAssignment_1");
					put(grammarAccess.getSurveyAccess().getQuestionsAssignment_3_0(), "rule__Survey__QuestionsAssignment_3_0");
					put(grammarAccess.getSurveyAccess().getQuestionsAssignment_3_1_1(), "rule__Survey__QuestionsAssignment_3_1_1");
					put(grammarAccess.getMultipleChoiceAccess().getQuestionAssignment_4_1(), "rule__MultipleChoice__QuestionAssignment_4_1");
					put(grammarAccess.getMultipleChoiceAccess().getChoiceAssignment_5_5(), "rule__MultipleChoice__ChoiceAssignment_5_5");
					put(grammarAccess.getMultipleChoiceAccess().getChoiceAssignment_5_6_1(), "rule__MultipleChoice__ChoiceAssignment_5_6_1");
					put(grammarAccess.getMultipleChoiceAccess().getOtherAssignment_6_4(), "rule__MultipleChoice__OtherAssignment_6_4");
					put(grammarAccess.getMultipleChoiceAccess().getMultipleChoiceForksAssignment_7_2(), "rule__MultipleChoice__MultipleChoiceForksAssignment_7_2");
					put(grammarAccess.getMultipleChoiceAccess().getMultipleChoiceForksAssignment_7_3_1(), "rule__MultipleChoice__MultipleChoiceForksAssignment_7_3_1");
					put(grammarAccess.getOpenAccess().getQuestionAssignment_4(), "rule__Open__QuestionAssignment_4");
					put(grammarAccess.getOpenAccess().getAnswerLengthAssignment_5_1(), "rule__Open__AnswerLengthAssignment_5_1");
					put(grammarAccess.getRating_ImplAccess().getRequiredAssignment_1(), "rule__Rating_Impl__RequiredAssignment_1");
					put(grammarAccess.getRating_ImplAccess().getQuestionAssignment_4_1(), "rule__Rating_Impl__QuestionAssignment_4_1");
					put(grammarAccess.getRating_ImplAccess().getMinAssignment_5_1(), "rule__Rating_Impl__MinAssignment_5_1");
					put(grammarAccess.getRating_ImplAccess().getMaxAssignment_6_1(), "rule__Rating_Impl__MaxAssignment_6_1");
					put(grammarAccess.getRating_ImplAccess().getFirstAssignment_7_1(), "rule__Rating_Impl__FirstAssignment_7_1");
					put(grammarAccess.getRating_ImplAccess().getLastAssignment_8_1(), "rule__Rating_Impl__LastAssignment_8_1");
					put(grammarAccess.getRating_ImplAccess().getRatingForksAssignment_9_2(), "rule__Rating_Impl__RatingForksAssignment_9_2");
					put(grammarAccess.getRating_ImplAccess().getRatingForksAssignment_9_3_1(), "rule__Rating_Impl__RatingForksAssignment_9_3_1");
					put(grammarAccess.getRankingAccess().getRequiredAssignment_0(), "rule__Ranking__RequiredAssignment_0");
					put(grammarAccess.getRankingAccess().getQuestionAssignment_3_1(), "rule__Ranking__QuestionAssignment_3_1");
					put(grammarAccess.getRankingAccess().getForksAssignment_4_2(), "rule__Ranking__ForksAssignment_4_2");
					put(grammarAccess.getRankingAccess().getForksAssignment_4_3_1(), "rule__Ranking__ForksAssignment_4_3_1");
					put(grammarAccess.getRankingAccess().getChoicesAssignment_7(), "rule__Ranking__ChoicesAssignment_7");
					put(grammarAccess.getRankingAccess().getChoicesAssignment_8_1(), "rule__Ranking__ChoicesAssignment_8_1");
					put(grammarAccess.getDichotomousAccess().getRequiredAssignment_1(), "rule__Dichotomous__RequiredAssignment_1");
					put(grammarAccess.getDichotomousAccess().getQuestionAssignment_4_1(), "rule__Dichotomous__QuestionAssignment_4_1");
					put(grammarAccess.getDichotomousAccess().getYesAssignment_5_2(), "rule__Dichotomous__YesAssignment_5_2");
					put(grammarAccess.getDichotomousAccess().getYesAssignment_5_3_1(), "rule__Dichotomous__YesAssignment_5_3_1");
					put(grammarAccess.getDichotomousAccess().getNoAssignment_6_2(), "rule__Dichotomous__NoAssignment_6_2");
					put(grammarAccess.getDichotomousAccess().getNoAssignment_6_3_1(), "rule__Dichotomous__NoAssignment_6_3_1");
					put(grammarAccess.getSumConstantAccess().getRequiredAssignment_1(), "rule__SumConstant__RequiredAssignment_1");
					put(grammarAccess.getSumConstantAccess().getQuestionAssignment_4_1(), "rule__SumConstant__QuestionAssignment_4_1");
					put(grammarAccess.getStapleAccess().getRequiredAssignment_1(), "rule__Staple__RequiredAssignment_1");
					put(grammarAccess.getStapleAccess().getQuestionAssignment_4_1(), "rule__Staple__QuestionAssignment_4_1");
					put(grammarAccess.getStapleAccess().getMinAssignment_5_1(), "rule__Staple__MinAssignment_5_1");
					put(grammarAccess.getStapleAccess().getMaxAssignment_6_1(), "rule__Staple__MaxAssignment_6_1");
					put(grammarAccess.getStapleAccess().getFirstAssignment_7_1(), "rule__Staple__FirstAssignment_7_1");
					put(grammarAccess.getStapleAccess().getLastAssignment_8_1(), "rule__Staple__LastAssignment_8_1");
					put(grammarAccess.getStapleAccess().getMidAssignment_9_1(), "rule__Staple__MidAssignment_9_1");
					put(grammarAccess.getStapleAccess().getRatingForksAssignment_10_2(), "rule__Staple__RatingForksAssignment_10_2");
					put(grammarAccess.getStapleAccess().getRatingForksAssignment_10_3_1(), "rule__Staple__RatingForksAssignment_10_3_1");
					put(grammarAccess.getChoiceAccess().getDescriptionAssignment(), "rule__Choice__DescriptionAssignment");
					put(grammarAccess.getMultipleChoiceForkAccess().getMatcherAssignment_2(), "rule__MultipleChoiceFork__MatcherAssignment_2");
					put(grammarAccess.getMultipleChoiceForkAccess().getForkedquestionsAssignment_3_2(), "rule__MultipleChoiceFork__ForkedquestionsAssignment_3_2");
					put(grammarAccess.getMultipleChoiceForkAccess().getForkedquestionsAssignment_3_3_1(), "rule__MultipleChoiceFork__ForkedquestionsAssignment_3_3_1");
					put(grammarAccess.getRatingForkAccess().getMinAssignment_3_1(), "rule__RatingFork__MinAssignment_3_1");
					put(grammarAccess.getRatingForkAccess().getMaxAssignment_4_1(), "rule__RatingFork__MaxAssignment_4_1");
					put(grammarAccess.getRatingForkAccess().getForkedquestionAssignment_5_2(), "rule__RatingFork__ForkedquestionAssignment_5_2");
					put(grammarAccess.getRatingForkAccess().getForkedquestionAssignment_5_3_1(), "rule__RatingFork__ForkedquestionAssignment_5_3_1");
					put(grammarAccess.getRankingForkAccess().getMinAssignment_2_1(), "rule__RankingFork__MinAssignment_2_1");
					put(grammarAccess.getRankingForkAccess().getMaxAssignment_3_1(), "rule__RankingFork__MaxAssignment_3_1");
					put(grammarAccess.getRankingForkAccess().getMatcherAssignment_5(), "rule__RankingFork__MatcherAssignment_5");
					put(grammarAccess.getRankingForkAccess().getForkedquestionsAssignment_6_2(), "rule__RankingFork__ForkedquestionsAssignment_6_2");
					put(grammarAccess.getRankingForkAccess().getForkedquestionsAssignment_6_3_1(), "rule__RankingFork__ForkedquestionsAssignment_6_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			dk.itu.mddp.eank.survey.ui.contentassist.antlr.internal.InternalSurveyParser typedParser = (dk.itu.mddp.eank.survey.ui.contentassist.antlr.internal.InternalSurveyParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SurveyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SurveyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
