/*
 * generated by Xtext
 */
package dk.itu.mddp.eank.survey.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSurveyValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/resource/dk.itu.mddp.eank.project/model/SurveyModel.ecore"));
		return result;
	}
}
