/**
 * generated by Xtext
 */
package dk.itu.mddp.eank.survey.serializer;

import dk.itu.mddp.eank.survey.serializer.AbstractSurveySyntacticSequencer;

@SuppressWarnings("all")
public class SurveySyntacticSequencer extends AbstractSurveySyntacticSequencer {
}
