/**
 * generated by Xtext
 */
package dk.itu.mddp.eank.survey.serializer;

import dk.itu.mddp.eank.survey.serializer.AbstractSurveySemanticSequencer;

@SuppressWarnings("all")
public class SurveySemanticSequencer extends AbstractSurveySemanticSequencer {
}
