/**
 * generated by Xtext
 */
package dk.itu.mddp.eank.survey.validation;

import dk.itu.mddp.eank.survey.validation.AbstractSurveyValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SurveyValidator extends AbstractSurveyValidator {
}
