/*
 * generated by Xtext
 */
package dk.itu.mddp.eank.survey;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SurveyRuntimeModule extends dk.itu.mddp.eank.survey.AbstractSurveyRuntimeModule {

}
